[package]
name = "gui"
version = "0.2.2"
edition = "2018"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0-or-later"
homepage = "https://crates.io/crates/gui"
repository = "https://github.com/d-e-s-o/gui.git"
readme = "README.md"
categories = ["gui", "command-line-utilities", "command-line-interface", "rendering"]
keywords = ["gui", "ui"]
description = """
A generic UI library/framework.
"""

[workspace]
members = ["derive"]

[badges]
gitlab = { repository = "d-e-s-o/gui", branch = "devel" }

[dev-dependencies.gui-derive]
version = "0.2"
path = "derive"
