[package]
name = "gui"
version = "0.1.0-alpha.1"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0+"
homepage = "https://crates.io/crates/gui"
repository = "https://github.com/d-e-s-o/gui.git"
readme = "README.md"
keywords = ["gui", "ui"]
description = """
A generic UI library/framework.
"""

[workspace]
members = ["derive"]

[dev-dependencies.gui-derive]
version = "0.1.0-alpha.1"
path = "derive"
