[package]
name = "gui-derive"
version = "0.2.2"
edition = "2018"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0-or-later"
homepage = "https://crates.io/crates/gui-derive"
repository = "https://github.com/d-e-s-o/gui.git"
readme = "README.md"
categories = ["gui", "command-line-utilities", "command-line-interface", "rendering"]
keywords = ["derive", "gui", "ui"]
description = """
Custom derive macros for the gui crate.
"""

[badges]
gitlab = { repository = "d-e-s-o/gui", branch = "devel" }

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "0.4"

[dependencies.quote]
version = "0.6"

[dependencies.syn]
version = "0.15"
default-features = false
features = ["derive", "parsing", "printing"]

[dev-dependencies.gui]
version = "0.2"
path = ".."
