[package]
name = "gui-derive"
version = "0.0.0"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0+"
homepage = "https://crates.io/crates/gui-derive"
repository = "https://github.com/d-e-s-o/gui.git"
readme = "README.md"
keywords = ["derive", "gui", "ui"]
description = """
Custom derive macros for the gui crate.
"""

[lib]
proc-macro = true

[dependencies.gui]
version = "0.0"
path = ".."

[dependencies.quote]
version = "0.4"

[dependencies.syn]
version = "0.12"
default-features = false
features = ["derive", "parsing", "printing"]
